redis-ha:
  enabled: false

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: false
    minReplicas: 1
  admin.enabled: "true"
  extraArgs:
    - --insecure

  config:
    kustomize.buildOptions: --enable-helm
    exec.enabled: "true"
    url: ${host}
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $eks-cluster-with-argo-sso:clientId
            clientSecret: $eks-cluster-with-argo-sso:clientSecret
            orgs:
            - name: ${github_org}
  rbacConfig:
    # policy.default is the name of the default role which Argo CD will falls back to, when
    # authorizing API requests (optional). If omitted or empty, users may be still be able to login,
    # but will see no apps, projects, etc...
    policy.default: role:readonly
    policy.csv: |
      ${indent(6, rbac_csv)}

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1